export enum RoleEnum {
  SUPER_ADMIN = 'SUPER_ADMIN',
  FACULTY_ADMIN = 'FACULTY_ADMIN',
  DEPARTMENT_ADMIN = 'DEPARTMENT_ADMIN',
  ADMIN = 'ADMIN', 
  INSTRUCTOR = 'INSTRUCTOR',
  STUDENT = 'STUDENT',
  MODERATOR = 'MODERATOR',
}
